### ISSUE TITLE
branches?

### ISSUE THREAD

**Issue by FKuerten** [iteratedecks/iteratedecks#58] opened 2013-04-02 20:11 UTC
What is the purpose of the staging branch?
What is the purpose of the test branch?

**Comment by MrHen** [comment] 2013-04-02 23:30
Test branch was for creating test cases. That can probably go away now because I have been using the test repo to add new tests.

Staging branch was intended to be a pre-release branch to keep the release branch clean but it didn't work out that way. I'm also not sure Git cares about things like that; in retrospect we could probably just get rid of it.

**Comment by MrHen** [comment] 2013-04-02 23:52
Okay, I deleted the staging branch. The tests branch was already deleted.

**Comment by FKuerten** [comment] 2013-04-03 00:40
test repo?

**Comment by MrHen** [comment] 2019-04-05 15:50
Archiving repo and closing all issues.

**Closed as completed by MrHen** 2019-04-05 15:50 UTC
Labels: question
